#!/bin/sh
# Clean Nginx-UI Installer - NO UCI TEMPLATE ERRORS

set -e

echo "=============================================="
echo "   Clean Nginx-UI Installer for OpenWrt"
echo "=============================================="

# Configuration
NGINX_UI_VERSION="v2.3.2"
NGINX_UI_URL="https://github.com/0xJacky/nginx-ui/releases/download/${NGINX_UI_VERSION}/nginx-ui-linux-64.tar.gz"
INSTALL_DIR="/opt/nginx-ui"
CONFIG_DIR="/etc/nginx-ui"
SERVICE_NAME="nginx-ui"
NGINX_UI_PORT="9000"
LUCI_PORT="8081"
PUBLIC_PORT="80"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Functions
print_status() { echo -e "${GREEN}[✓]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[!]${NC} $1"; }
print_error() { echo -e "${RED}[✗]${NC} $1"; }

get_router_ip() {
    uci get network.lan.ipaddr 2>/dev/null || echo "192.168.100.1"
}

clean_install() {
    print_status "Performing clean installation..."
    
    # 1. STOP EVERYTHING
    /etc/init.d/nginx stop 2>/dev/null
    /etc/init.d/uhttpd stop 2>/dev/null
    killall nginx-ui 2>/dev/null
    
    # 2. REMOVE NGINX COMPLETELY
    print_status "Removing nginx packages..."
    opkg remove --force-removal-of-dependent-packages nginx nginx-* 2>/dev/null || true
    
    # 3. CLEAN DIRECTORIES
    print_status "Cleaning directories..."
    rm -rf /etc/nginx /var/lib/nginx /usr/lib/nginx /var/log/nginx 2>/dev/null
    mkdir -p /etc/nginx /var/log/nginx /etc/nginx/conf.d
    
    # 4. INSTALL NGINX WITHOUT MODULES
    print_status "Installing nginx (no modules)..."
    opkg update
    
    # First install nginx-util (for templates)
    if ! opkg install nginx-util; then
        print_warning "nginx-util not available, creating manual..."
        # Create missing template manually
        mkdir -p /usr/bin
        cat > /usr/bin/nginx-util << 'EOF'
#!/bin/sh
# Dummy nginx-util script
echo "nginx-util dummy script"
exit 0
EOF
        chmod +x /usr/bin/nginx-util
    fi
    
    # Install nginx package
    opkg install nginx
    
    # 5. CREATE REQUIRED TEMPLATE FILES
    print_status "Creating required template files..."
    
    # Create uci.conf.template
    mkdir -p /etc/nginx
    cat > /etc/nginx/uci.conf.template << 'EOF'
# Nginx UCI configuration template
# This file is auto-generated by nginx-util

# Main configuration
user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    include /etc/nginx/conf.d/*.conf;
}
EOF

    # Create config directory
    mkdir -p /var/lib/nginx
    
    # Create initial nginx config
    cat > /etc/nginx/nginx.conf << 'EOF'
# Main nginx configuration
user nobody nogroup;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    include /etc/nginx/conf.d/*.conf;
}
EOF

    # 6. DISABLE NGINX AUTO-START
    /etc/init.d/nginx disable 2>/dev/null
    
    print_status "Clean installation complete"
}

download_nginx_ui() {
    print_status "Downloading nginx-ui ${NGINX_UI_VERSION}..."
    
    mkdir -p $INSTALL_DIR
    cd /tmp
    
    # Clean previous downloads
    rm -f nginx-ui.tar.gz
    
    print_status "Download URL: $NGINX_UI_URL"
    
    # Download with retry
    for i in 1 2 3; do
        if wget --no-check-certificate -O nginx-ui.tar.gz "$NGINX_UI_URL"; then
            break
        elif curl -L -k -o nginx-ui.tar.gz "$NGINX_UI_URL"; then
            break
        else
            print_warning "Attempt $i failed, retrying..."
            sleep 2
        fi
    done
    
    if [ ! -f "nginx-ui.tar.gz" ]; then
        print_error "Download failed after 3 attempts"
        return 1
    fi
    
    # Extract
    tar -xzf nginx-ui.tar.gz 2>/dev/null || {
        gzip -dc nginx-ui.tar.gz | tar -x
    }
    
    # Find binary
    if [ -f "nginx-ui" ]; then
        mv nginx-ui $INSTALL_DIR/
    else
        # Try to find any executable
        find /tmp -name "*nginx-ui*" -type f -executable 2>/dev/null | head -1 | xargs -I {} cp {} $INSTALL_DIR/nginx-ui
    fi
    
    if [ ! -f "$INSTALL_DIR/nginx-ui" ]; then
        # List extracted files
        print_status "Extracted files:"
        find /tmp -type f -name "*" | head -10
        return 1
    fi
    
    chmod +x $INSTALL_DIR/nginx-ui
    
    print_status "nginx-ui binary ready"
    return 0
}

create_nginx_config_final() {
    print_status "Creating final nginx configuration..."
    
    ROUTER_IP=$(get_router_ip)
    
    # Clean conf.d
    rm -rf /etc/nginx/conf.d
    mkdir -p /etc/nginx/conf.d
    
    # Main configuration
    cat > /etc/nginx/conf.d/main.conf << EOF
# OpenWrt Router Configuration
# Main server block

server {
    listen ${PUBLIC_PORT};
    server_name _;
    
    # Root redirect to dashboard
    location = / {
        return 302 /dashboard/;
    }
    
    # Dashboard interface
    location /dashboard/ {
        alias /www/dashboard/;
        index index.html;
        
        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        
        # Cache static files
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, immutable";
        }
    }
    
    # Nginx-UI interface
    location /ui/ {
        proxy_pass http://127.0.0.1:${NGINX_UI_PORT}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # Luci interface (original OpenWrt)
    location /luci/ {
        proxy_pass http://127.0.0.1:${LUCI_PORT}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
    
    # Health check endpoint
    location /health {
        return 200 'healthy\n';
        add_header Content-Type text/plain;
    }
    
    # Status endpoint
    location /status {
        proxy_pass http://127.0.0.1:${NGINX_UI_PORT}/api/status;
        proxy_set_header Host \$host;
    }
    
    # Default error page
    error_page 404 /dashboard/404.html;
    error_page 500 502 503 504 /dashboard/50x.html;
}
EOF

    # Create a default virtual host for unknown domains
    cat > /etc/nginx/conf.d/default.conf << EOF
# Default catch-all server
server {
    listen ${PUBLIC_PORT} default_server;
    server_name _;
    
    return 444;  # Close connection without response
}
EOF

    print_status "Nginx configuration created"
}

create_nginx_ui_config() {
    print_status "Configuring nginx-ui..."
    
    mkdir -p $CONFIG_DIR
    mkdir -p $INSTALL_DIR/{data,logs}
    
    # Create config.yaml for nginx-ui v2.3.2
    cat > $CONFIG_DIR/config.yaml << 'EOF'
# Nginx-UI Configuration
server:
  host: "127.0.0.1"
  port: 9000
  log_path: "/opt/nginx-ui/logs/nginx-ui.log"
  read_timeout: 60
  write_timeout: 60
  max_header_bytes: 1048576

nginx:
  config_dir: "/etc/nginx"
  pid_path: "/var/run/nginx.pid"
  test_config_cmd: "nginx -t"
  reload_cmd: "nginx -s reload"
  restart_cmd: "/etc/init.d/nginx restart"
  access_log_path: "/var/log/nginx/access.log"
  error_log_path: "/var/log/nginx/error.log"

database:
  path: "/opt/nginx-ui/data/nginx-ui.db"
  max_idle_conns: 5
  max_open_conns: 10

log:
  level: "info"
  encoding: "console"
  disable_caller: false
  disable_stacktrace: false
EOF

    # Also create config.json for compatibility
    cat > $CONFIG_DIR/config.json << EOF
{
    "server": {
        "host": "127.0.0.1",
        "port": ${NGINX_UI_PORT},
        "log_path": "${INSTALL_DIR}/logs/nginx-ui.log"
    },
    "nginx": {
        "config_path": "/etc/nginx/nginx.conf",
        "config_dir": "/etc/nginx",
        "pid_path": "/var/run/nginx.pid",
        "test_config_cmd": "nginx -t",
        "reload_cmd": "nginx -s reload",
        "restart_cmd": "/etc/init.d/nginx restart"
    }
}
EOF

    print_status "nginx-ui configuration created"
}

setup_uhttpd_properly() {
    print_status "Configuring uHTTPd (Luci)..."
    
    # Backup original
    if [ -f /etc/config/uhttpd ]; then
        cp /etc/config/uhttpd /etc/config/uhttpd.original.backup
    fi
    
    # Stop uHTTPd
    /etc/init.d/uhttpd stop 2>/dev/null
    sleep 2
    
    # Create minimal working config
    cat > /etc/config/uhttpd << 'EOF'
config uhttpd 'main'
    option listen_http '127.0.0.1:8081'
    option listen_https '127.0.0.1:8081'
    option home '/www'
    option rfc1918_filter '1'
    option max_requests '3'
    option max_connections '100'
    option cert '/etc/uhttpd.crt'
    option key '/etc/uhttpd.key'
    option cgi_prefix '/cgi-bin'
    
config uhttpd 'ubus'
    option socket '/var/run/ubus/ubus.sock'
EOF
    
    # Create self-signed cert if not exists
    if [ ! -f /etc/uhttpd.crt ]; then
        openssl req -new -x509 -nodes -days 365 -subj "/CN=openwrt" \
            -keyout /etc/uhttpd.key -out /etc/uhttpd.crt 2>/dev/null || true
    fi
    
    # Restart uHTTPd
    /etc/init.d/uhttpd start
    sleep 3
    
    # Verify it's running
    if ps | grep -q "[u]httpd"; then
        print_status "✓ uHTTPd (Luci) running on 127.0.0.1:8081"
    else
        print_error "✗ uHTTPd failed to start"
        # Try default config
        cp /etc/config/uhttpd.original.backup /etc/config/uhttpd 2>/dev/null
        /etc/init.d/uhttpd start
    fi
}

create_nginx_ui_service() {
    print_status "Creating nginx-ui service..."
    
    cat > /etc/init.d/$SERVICE_NAME << 'EOF'
#!/bin/sh /etc/rc.common
# nginx-ui service for OpenWrt

USE_PROCD=1
START=99
STOP=10

PROG="/opt/nginx-ui/nginx-ui"
CONFIG="/etc/nginx-ui/config.yaml"
LOG_FILE="/opt/nginx-ui/logs/service.log"

validate_service() {
    if [ ! -x "$PROG" ]; then
        logger -t nginx-ui "Error: $PROG not executable"
        return 1
    fi
    
    if [ ! -f "$CONFIG" ]; then
        logger -t nginx-ui "Warning: Config $CONFIG not found, using defaults"
    fi
    
    return 0
}

start_service() {
    if ! validate_service; then
        return 1
    fi
    
    # Create log directory
    mkdir -p "$(dirname "$LOG_FILE")"
    
    procd_open_instance
    procd_set_param command "$PROG" -config "$CONFIG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_set_param env NGINX_UI_INSTANCE=openwrt
    procd_set_param file "$CONFIG"
    procd_close_instance
    
    logger -t nginx-ui "Service started"
}

stop_service() {
    logger -t nginx-ui "Stopping service..."
    killall nginx-ui 2>/dev/null
    sleep 1
}
EOF

    chmod +x /etc/init.d/$SERVICE_NAME
    /etc/init.d/$SERVICE_NAME enable
    
    print_status "nginx-ui service created"
}

create_dashboard_simple() {
    print_status "Creating dashboard..."
    
    mkdir -p /www/dashboard
    
    # Main dashboard
    cat > /www/dashboard/index.html << 'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenWrt Router Manager</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }
        .container {
            background: rgba(255, 255, 255, 0.95);
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            max-width: 500px;
            width: 100%;
            text-align: center;
            backdrop-filter: blur(10px);
        }
        .logo {
            font-size: 60px;
            margin-bottom: 20px;
            color: #667eea;
        }
        h1 {
            color: #2c3e50;
            margin-bottom: 10px;
            font-size: 28px;
        }
        .subtitle {
            color: #7f8c8d;
            margin-bottom: 30px;
            font-size: 16px;
        }
        .ip-box {
            background: #e3f2fd;
            padding: 15px;
            border-radius: 10px;
            margin: 20px 0;
            font-family: 'Courier New', monospace;
            font-size: 20px;
            font-weight: bold;
            color: #1976d2;
        }
        .btn {
            display: block;
            width: 100%;
            padding: 16px;
            margin: 12px 0;
            border: none;
            border-radius: 10px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            text-decoration: none;
            text-align: center;
            transition: all 0.3s;
        }
        .btn-primary {
            background: #4CAF50;
            color: white;
        }
        .btn-primary:hover {
            background: #45a049;
            transform: translateY(-2px);
            box-shadow: 0 5px 15px rgba(0,0,0,0.2);
        }
        .btn-secondary {
            background: #2196F3;
            color: white;
        }
        .btn-secondary:hover {
            background: #1976D2;
            transform: translateY(-2px);
        }
        .btn-warning {
            background: #FF9800;
            color: white;
        }
        .status-box {
            background: #f8f9fa;
            border-radius: 10px;
            padding: 20px;
            margin: 20px 0;
            text-align: left;
        }
        .status-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px 0;
            border-bottom: 1px solid #eee;
        }
        .status-item:last-child {
            border-bottom: none;
        }
        .status-dot {
            width: 12px;
            height: 12px;
            border-radius: 50%;
            display: inline-block;
            margin-right: 10px;
        }
        .status-running { background: #4CAF50; }
        .status-stopped { background: #f44336; }
        .status-unknown { background: #FF9800; }
        footer {
            margin-top: 30px;
            color: #95a5a6;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">🚀</div>
        <h1>OpenWrt Router Manager</h1>
        <p class="subtitle">Centralized management interface</p>
        
        <div class="ip-box" id="router-ip">192.168.1.1</div>
        
        <a href="/ui/" class="btn btn-primary" target="_blank">
            📊 Open Nginx-UI Dashboard
        </a>
        
        <a href="/luci/" class="btn btn-secondary" target="_blank">
            ⚙️ Open Luci Interface
        </a>
        
        <a href="/health" class="btn btn-warning" target="_blank">
            🩺 System Health Check
        </a>
        
        <div class="status-box">
            <h3 style="margin-bottom: 15px; color: #2c3e50;">Service Status</h3>
            <div class="status-item">
                <span>Nginx Web Server</span>
                <span>
                    <span class="status-dot" id="nginx-dot"></span>
                    <span id="nginx-text">Checking...</span>
                </span>
            </div>
            <div class="status-item">
                <span>Nginx-UI Manager</span>
                <span>
                    <span class="status-dot" id="nginxui-dot"></span>
                    <span id="nginxui-text">Checking...</span>
                </span>
            </div>
            <div class="status-item">
                <span>Luci Interface</span>
                <span>
                    <span class="status-dot" id="luci-dot"></span>
                    <span id="luci-text">Checking...</span>
                </span>
            </div>
        </div>
        
        <button onclick="checkAllStatus()" style="
            background: #9c27b0;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 14px;
            cursor: pointer;
            margin-top: 10px;
            width: 100%;
        ">
            🔄 Refresh Status
        </button>
        
        <footer>
            <p>OpenWrt Router | Nginx-UI v2.3.2</p>
            <p id="current-time"></p>
        </footer>
    </div>

    <script>
    function updateTime() {
        const now = new Date();
        document.getElementById('current-time').textContent = 
            now.toLocaleDateString() + ' ' + now.toLocaleTimeString();
    }
    
    async function checkStatus(service, elementId, dotId) {
        try {
            const endpoints = {
                nginx: '/health',
                nginxui: '/ui/',
                luci: '/luci/'
            };
            
            const response = await fetch(endpoints[service], { method: 'HEAD' });
            const element = document.getElementById(elementId);
            const dot = document.getElementById(dotId);
            
            if (response.ok) {
                element.textContent = 'Running';
                dot.className = 'status-dot status-running';
                return true;
            }
        } catch (error) {
            // Try alternative
            try {
                const altResponse = await fetch('/status');
                if (altResponse.ok) {
                    document.getElementById(elementId).textContent = 'Running';
                    document.getElementById(dotId).className = 'status-dot status-running';
                    return true;
                }
            } catch (e) {
                // Fall through
            }
        }
        
        document.getElementById(elementId).textContent = 'Stopped';
        document.getElementById(dotId).className = 'status-dot status-stopped';
        return false;
    }
    
    function checkAllStatus() {
        checkStatus('nginx', 'nginx-text', 'nginx-dot');
        checkStatus('nginxui', 'nginxui-text', 'nginxui-dot');
        checkStatus('luci', 'luci-text', 'luci-dot');
    }
    
    // Get router IP
    async function getRouterIP() {
        try {
            // Try multiple methods
            const methods = [
                fetch('/ip').then(r => r.json()).then(data => data.ip),
                fetch('/api/ip').then(r => r.json()).then(data => data.ip),
                Promise.resolve('192.168.1.1')
            ];
            
            for (const method of methods) {
                try {
                    const ip = await method;
                    if (ip && ip !== 'undefined') {
                        document.getElementById('router-ip').textContent = ip;
                        break;
                    }
                } catch (e) {
                    continue;
                }
            }
        } catch (e) {
            document.getElementById('router-ip').textContent = '192.168.1.1';
        }
    }
    
    // Initialize
    updateTime();
    setInterval(updateTime, 1000);
    
    getRouterIP();
    checkAllStatus();
    
    // Auto-refresh status every 30 seconds
    setInterval(checkAllStatus, 30000);
    
    // Initial delay for services to start
    setTimeout(checkAllStatus, 5000);
    </script>
</body>
</html>
HTML

    # Create error pages
    cat > /www/dashboard/404.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>404 - Not Found</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        h1 { color: #e74c3c; }
        a { color: #3498db; text-decoration: none; }
    </style>
</head>
<body>
    <h1>404 - Page Not Found</h1>
    <p>The requested page was not found.</p>
    <p><a href="/dashboard/">Return to Dashboard</a></p>
</body>
</html>
EOF

    cat > /www/dashboard/50x.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>50x - Server Error</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        h1 { color: #e74c3c; }
        a { color: #3498db; text-decoration: none; }
    </style>
</head>
<body>
    <h1>50x - Server Error</h1>
    <p>Something went wrong on the server.</p>
    <p><a href="/dashboard/">Return to Dashboard</a></p>
</body>
</html>
EOF

    # Create IP endpoint
    get_router_ip > /www/dashboard/ip
}

start_all_services() {
    print_status "Starting all services..."
    
    # 1. Start uHTTPd (Luci)
    print_status "Starting uHTTPd (Luci)..."
    /etc/init.d/uhttpd start
    sleep 3
    
    # 2. Start nginx-ui
    print_status "Starting nginx-ui..."
    /etc/init.d/nginx-ui start
    sleep 5
    
    # 3. Start nginx
    print_status "Starting nginx..."
    /etc/init.d/nginx start
    sleep 5
    
    # Check services
    print_status "Verifying services..."
    
    local errors=0
    
    if ps | grep -q "[u]httpd"; then
        print_status "✓ uHTTPd (Luci) is running"
    else
        print_error "✗ uHTTPd failed to start"
        errors=$((errors + 1))
    fi
    
    if ps | grep -q "[n]ginx-ui"; then
        print_status "✓ nginx-ui is running"
    else
        print_error "✗ nginx-ui failed to start"
        errors=$((errors + 1))
    fi
    
    if ps | grep -q "[n]ginx.*master"; then
        print_status "✓ nginx is running"
    else
        print_error "✗ nginx failed to start"
        errors=$((errors + 1))
    fi
    
    if [ $errors -eq 0 ]; then
        print_status "✅ All services started successfully!"
    else
        print_warning "⚠ Some services failed to start (${errors} errors)"
    fi
}

setup_firewall_simple() {
    print_status "Configuring firewall..."
    
    if [ -f /etc/config/firewall ]; then
        # Add rule for port 80
        uci add firewall rule
        uci set firewall.@rule[-1].name='Web-Management'
        uci set firewall.@rule[-1].src='wan'
        uci set firewall.@rule[-1].dest_port='80'
        uci set firewall.@rule[-1].proto='tcp'
        uci set firewall.@rule[-1].target='ACCEPT'
        uci commit firewall
        
        # Reload firewall
        if /etc/init.d/firewall enabled; then
            /etc/init.d/firewall reload
        fi
        
        print_status "Firewall configured for port 80"
    else
        print_warning "Firewall not installed, skipping"
    fi
}

print_final_summary() {
    ROUTER_IP=$(get_router_ip)
    
    echo ""
    echo "=============================================="
    echo "   🎉 INSTALLATION COMPLETE! 🎉"
    echo "=============================================="
    echo ""
    echo "📡 NETWORK INFORMATION:"
    echo "   Router IP:        ${ROUTER_IP}"
    echo "   Public Port:      80"
    echo ""
    echo "🌐 ACCESS POINTS:"
    echo "   1. Main Dashboard:    http://${ROUTER_IP}/"
    echo "   2. Nginx-UI Admin:    http://${ROUTER_IP}/ui/"
    echo "   3. Luci Interface:    http://${ROUTER_IP}/luci/"
    echo "   4. Health Check:      http://${ROUTER_IP}/health"
    echo ""
    echo "🔐 DEFAULT CREDENTIALS:"
    echo "   • Nginx-UI: admin / admin"
    echo "   • Luci:     Your existing OpenWrt credentials"
    echo ""
    echo "⚙️ SERVICE MANAGEMENT:"
    echo "   Restart nginx:        /etc/init.d/nginx restart"
    echo "   Restart nginx-ui:     /etc/init.d/nginx-ui restart"
    echo "   Restart Luci:         /etc/init.d/uhttpd restart"
    echo ""
    echo "📊 LOGS LOCATION:"
    echo "   Nginx error log:      /var/log/nginx/error.log"
    echo "   Nginx access log:     /var/log/nginx/access.log"
    echo "   Nginx-UI log:         /opt/nginx-ui/logs/nginx-ui.log"
    echo ""
    echo "🛠️ TROUBLESHOOTING:"
    echo "   If services don't start:"
    echo "     1. Check logs: tail -f /var/log/nginx/error.log"
    echo "     2. Test nginx: nginx -t"
    echo "     3. Check ports: netstat -tlnp"
    echo ""
    echo "   To revert to original Luci:"
    echo "     1. Stop nginx: /etc/init.d/nginx stop"
    echo "     2. Restore uHTTPd: cp /etc/config/uhttpd.original.backup /etc/config/uhttpd"
    echo "     3. Restart uHTTPd: /etc/init.d/uhttpd restart"
    echo ""
    echo "=============================================="
    echo "   Open your browser and visit:"
    echo "          http://${ROUTER_IP}/"
    echo "=============================================="
    echo ""
}

# Main installation
main() {
    echo "Starting clean installation of Nginx-UI v2.3.2"
    echo "This will install and configure everything automatically."
    echo ""
    
    # Check root
    if [ "$(id -u)" -ne 0 ]; then
        print_error "This script must be run as root"
        exit 1
    fi
    
    # Perform installation steps
    clean_install
    download_nginx_ui
    create_nginx_config_final
    create_nginx_ui_config
    setup_uhttpd_properly
    create_nginx_ui_service
    create_dashboard_simple
    start_all_services
    setup_firewall_simple
    print_final_summary
    
    # Final test
    echo ""
    print_status "Performing final test..."
    sleep 5
    
    if curl -s "http://127.0.0.1/health" 2>/dev/null | grep -q "healthy"; then
        print_status "✅ Installation successful! All systems operational."
    else
        print_warning "⚠ Some services may need manual intervention"
        print_status "Try accessing: http://$(get_router_ip)/"
    fi
}

# Run installation
main "$@"
